### ISSUE TITLE
Bug with duplicates suggests

### ISSUE THREAD

**Issue by trasher** [solariumphp/solarium#252] opened 2014-04-03 12:07 UTC
Hello,

I currently ha a suggest query which returns duplicates:

``` xml
<response>
  <lst name="responseHeader">
    <int name="status">0</int>
    <int name="QTime">0</int>
  </lst>
  <lst name="spellcheck">
    <lst name="suggestions">
      <lst name="commerce">
        <int name="numFound">3</int>
        <int name="startOffset">0</int>
        <int name="endOffset">8</int>
        <arr name="suggestion">
          <str>commercer</str>
          <str>commerces</str>
          <str>commerceà</str>
        </arr>
      </lst>
      <lst name="commerce">
        <int name="numFound">3</int>
        <int name="startOffset">9</int>
        <int name="endOffset">17</int>
        <arr name="suggestion">
          <str>commercer</str>
          <str>commerces</str>
          <str>commerceà</str>
        </arr>
      </lst>
    </lst>
  </lst>
</response>
```

It should not be an usual case, but it happens here because we have the same term twice (commerce) in the original query.

With such a result, I got the following error:
ContextErrorException: Notice: Undefined index: numFound in [...]/vendor/solarium/solarium/library/Solarium/QueryType/Suggester/ResponseParser.php line 78

**Comment by thomascorthals** [comment] 2020-07-02 11:46
This looks like a duplicate of or at least related to #184.

**Closed** 2022-04-04 11:47 UTC
Labels: Bug
