### ISSUE TITLE
Facet pivot stats fields overwritten when calling getFacetSet()

### ISSUE THREAD

**Issue by kiprasbiel** [solariumphp/solarium#1059] opened 2023-04-04 14:00 UTC
**Solarium version(s) affected**: 6.2.8
**Solr version**:8.11.1

**Description**  

Trying to implement Solr [Combining Stats Component With Pivots](https://solr.apache.org/guide/faceting.html#combining-stats-component-with-pivots) using Solarium. But when trying to access the stats results using getFacetSet() only last stat field exists.

**How to reproduce**  

Creating new FacetPivot _piv1_ and adding  _mediaType_ as pivot field.

Two stats fields are then created using $stats->createField(). These fields calculate the sum of the 'price' and 'views' fields, respectively, for each pivot value in the _piv1_ facet.

```
$query = $this->client->createSelect($select);

$facetSet = $query->getFacetSet();
$stats = $query->getStats();

// Creating pivot
$facet = $facetSet->createFacetPivot('piv1');
$facet->addFields('{!stats=piv1}mediaType');

// Creating stats fields
$stats->createField('{!tag=piv1 sum=true}price');
$stats->createField('{!tag=piv1 sum=true}views');

$resultSet = $this->client->select($query);
```

in `$resultSet` _body_ everything is fetched correctly ( _stats_field->price_ and _stats_field->views_ are visible):
```
{
  "facet_counts": {
    "facet_pivot": {
      "piv1": [
        {
          "field": "mediaType",
          "value": "int",
          "count": 39,
          "stats": {
            "stats_fields": {
              "price": {
                "sum": 7182.340007781982
              },
              "views": {
                "sum": 220416.0
              }
            }
          }
        }
      ]
    }
  }
}
```

But calling `$resultSet->getFacetSet()` only _stats_fields->views_ are left and _stats_field->price_  is lost. 

```
^ Solarium\Component\Result\FacetSet^ {#3809
  #facets: array:1 [
    "piv1" => Solarium\Component\Result\Facet\Pivot\Pivot^ {#3802
      #pivot: array:1 [
        0 => Solarium\Component\Result\Facet\Pivot\PivotItem^ {#3806
          #pivot: []
          #field: "mediaType"
          #value: "int"
          #count: 39
          #stats: Solarium\Component\Result\Stats\Stats^ {#3807
            #results: array:1 [
              "stats_fields" => Solarium\Component\Result\Stats\Result^ {#3811
                #field: "views"
                #stats: array:1 [
                  "sum" => 220416.0
                ]
              }
            ]
          }
          #ranges: null
        }
      ]
    }
  ]
}

```

**Possible Solution**  
It seems that the stats field is being overwritten in \Solarium\Component\ResponseParser\FacetSet::pivotStats. 

```
protected function pivotStats(PivotItem $pivotItem): void
    {
        foreach ($pivotItem->getPivot() as $pivot) {
            $this->pivotStats($pivot);
        }

        if (null !== $stats = $pivotItem->getStats()) {
            foreach ($stats->getResults() as $key => $result) {
                if ($result instanceof Result || false === \is_array($result)) {
                    continue;
                }

                foreach ($result as $field => $values) {
                    $stats->setResult($key, new Result($field, $values)); // Bug?
                }
            }
        }
    }
```

Here the `new Result($field, $values)` fetches everything correctly, but `$stats->setResult` saves both results with the same `$key`, hence only single stats_field being left. 

**Additional context**  

Maybe this is not how I should try to fetch stats from pivots?

**Comment by thomascorthals** [comment] 2023-05-07 10:59
Looks like a bug indeed.

I reproduced it against techproducts, should go in an integration test when we're able to fix this.

```php
$query = $this->client->createSelect($select);

$facetSet = $query->getFacetSet();
$stats = $query->getStats();

// Creating pivot
$facet = $facetSet->createFacetPivot('piv1');
$facet->addFields('{!stats=piv1}cat');

// Creating stats fields
$stats->createField('{!tag=piv1 sum=true}price');
$stats->createField('{!tag=piv1 sum=true}popularity');

// this executes the query and returns the result
resultSet = $this->client->select($query);
```

**Comment by thomascorthals** [comment] 2023-07-16 09:44
Fixing this will break backward comptability. I don't see a way around that.

Doesn't mean that it shouldn't be fixed. Just gonna take some extra effort to document the change.

**Comment by thomascorthals** [comment] 2023-10-29 23:00
@kiprasbiel #1102 should fix this, but I'd really like an extra pair of eyes on that code. I've never used this functionality myself.

The BC break isn't actually that bad. You have to use `->getResult('price')` now where it was previously `->getResult('stats_fields')`. Looping over `->getResults()` you won't even notice this change if you don't look at the key.

There were two other small issues with mean and percentiles that had already been fixed for other stats and are now fixed with facet pivot stats as well.

**Closed** 2023-11-09 15:17 UTC
Labels: Bug

**Comment by thomascorthals** [comment] 2023-12-04 12:25
@kiprasbiel [Solarium 6.3.4](https://github.com/solariumphp/solarium/releases/tag/6.3.4) has been released with the fix for this issue.
