### ISSUE TITLE
Parallel Plugin Timeout Error if Caching enabled

### ISSUE THREAD

**Issue by ScherlOMatic** [solariumphp/solarium#313] opened 2015-02-26 18:07 UTC
Hello!

After switching from single to parallel execution we are experiencing problems (timeouts) when caching (apcu + opcache) is enabled. It's kind of hard to reproduce cause sometimes it works and sometimes it fails. Another weird thing is that it's always a different request that fails.
We also noticed that it works with fewer parallel requests just fine but after a certain threshold everything goes crazy...

Are there any cache related problems known or do you have any idea how i can narrow down the problem?

If you need more details about the project plz let me know.

The server is running on centos 6.5 with php 5.5.21, apache 2.2.15 and curl 7.19.7.
Solarium is running on v3 dev-master

thx stefan

**Comment by basdenooijer** [comment] 2015-03-13 11:01
I've never experienced such issues, while I have used parallel execution in combination with apcu. But never a large number of requests (max 4).
Also, I'm not sure where you should start with debugging this. What do you mean with "everything goes crazy"?

Could you create a script that reproduces the issue?

**Comment by mkalkbrenner** [comment] 2020-06-10 09:21
Since this issue is 5 years old I close it.
A lot of things changed in solarium and we should wait until a new bug report is created if someone is running into that again.

**Closed by mkalkbrenner** 2020-06-10 09:21 UTC
