### ISSUE TITLE
Buggy `BufferedAdd` documentation/implementation

### ISSUE THREAD

**Issue by floriansemm** [solariumphp/solarium#433] opened 2016-06-27 07:29 UTC
I don't know exactly if it is a documentation or implementation bug: 

In the documentation you run at the end `$buffer->flush()`. In this case I would expect some documents in my index, but no documents are indexed. If I add a `$this->updateQuery->addCommit();` inside of the `flush` method, then documents are indexed. The example should be work if `flush` method will be replaced by `commit`.

So I don't if my "fix" is needed or the documentation needs to be updated.

**Comment by basdenooijer** [comment] 2016-08-30 07:37
I think documentation needs to be updated, because the behavior of flush and commit is by design:

- flush only flushes any remaining documents to Solr, without committing. This is important when using a solr autocommit strategy.
- commit checks the buffer first, and if needed flushes documents, followed by a commit. So commit is basically flush + commit

**Comment by thomascorthals** [comment] 2020-08-13 16:20
The difference between a `flush` and a `commit` is mentioned in the docs and example.

https://github.com/solariumphp/solarium/blob/5e1c6e2489762372cb382809e76838c24aac9a0c/docs/plugins.md#L18-L20

https://github.com/solariumphp/solarium/blob/5e1c6e2489762372cb382809e76838c24aac9a0c/examples/7.5-plugin-bufferedadd.php#L37-L38

@mkalkbrenner Is this sufficient to close this issue?

**Comment by mkalkbrenner** [comment] 2020-08-13 16:43
thanks!

**Closed by mkalkbrenner** 2020-08-13 16:43 UTC
