### ISSUE TITLE
Solr HTTP error: HTTP request failed, Failed to connect to 127.0.0.1 port 8983 after 

### ISSUE THREAD

**Issue by vishalinfyom** [solariumphp/solarium#988] opened 2022-03-21 06:23 UTC
**Solr version**:6.0.4

**Description**  
Getting below errors when trying to search records : 

Solr HTTP error: HTTP request failed, Failed to connect to 127.0.0.1 port 8983 after 0 ms: Connection refused {"exception":"[object] (Solarium\\Exception\\HttpException(code: 0): Solr HTTP error: HTTP request failed, Failed to connect to 127.0.0.1 port 8983 after 0 ms: Connection refused at /path/vendor/solarium/solarium/src/Core/Client/Adapter/Curl.php:172

**Comment by thomascorthals** [comment] 2022-03-21 10:22
There is no Solr 6.0.4 release so I assume you mean Solarium 6.0.4. How did you determine this version? Solarium 6.1.0 accidentally declared itself as 6.0.4 too, so you might have that version if you based it off `Client::VERSION`. Not that I think it really matters.

Have you tried `solr status` to verify that there is a Solr process running and listening on that port? It will either look something like this:
```
Found Solr process 45548 running on port 8983
{
  "solr_home":"C:\\solr-8.11.1\\example\\techproducts\\solr",
  "version":"8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:50:55",
  "startTime":"2022-03-17T21:35:29.948Z",
  "uptime":"3 days, 12 hours, 42 minutes, 38 seconds",
  "memory":"302.8 MB (%59.1) of 512 MB"}
```
or this:
```
No running Solr nodes found.
```

**Comment by thomascorthals** [comment] 2022-03-31 17:40
@vishalinfyom Did you manage to sort this?

If I had to guess, I'd say that either:
- you were trying to connect to a Solr instance on localhost that wasn't running;
- you meant to connect to a Solr instance on a remote host and didn't update the endpoint config accordingly.

**Comment by thomascorthals** [comment] 2022-05-01 16:39
Closing this as I think it isn't caused by Solarium. Don't hesitate to reopen if it is.

**Closed by thomascorthals** 2022-05-01 16:39 UTC
Labels: help wanted
